import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import Navbar from "./_components/Navbar";
import PromoBar from "./_components/PromoBar";

const font = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={font.className}>
      <body className='flex flex-col h-dvh'>
        <TRPCReactProvider>
          {/* Navbar & PromoBar */}
          <Navbar/>
          <PromoBar/>

          {/* Children */}
          <div className='flex-grow'>
            {children}
          </div>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
