export const categories = [
  { name: "Electronics" },
  { name: "Mobile Phones" },
  { name: "Laptops" },
  { name: "Tablets" },
  { name: "Cameras" },
  { name: "Headphones" },
  { name: "Wearable Technology" },
  { name: "Home Appliances" },
  { name: "Kitchen Appliances" },
  { name: "Furniture" },
  { name: "Home Decor" },
  { name: "Bedding" },
  { name: "Bath" },
  { name: "Garden & Outdoor" },
  { name: "Tools & Hardware" },
  { name: "Lighting" },
  { name: "Office Supplies" },
  { name: "Stationery" },
  { name: "Toys" },
  { name: "Games" },
  { name: "Books" },
  { name: "eBooks" },
  { name: "Music" },
  { name: "Movies" },
  { name: "Video Games" },
  { name: "Board Games" },
  { name: "Clothing - Men" },
  { name: "Clothing - Women" },
  { name: "Clothing - Kids" },
  { name: "Shoes - Men" },
  { name: "Shoes - Women" },
  { name: "Shoes - Kids" },
  { name: "Jewelry" },
  { name: "Watches" },
  { name: "Bags & Luggage" },
  { name: "Beauty & Personal Care" },
  { name: "Skincare" },
  { name: "Haircare" },
  { name: "Makeup" },
  { name: "Fragrances" },
  { name: "Health & Wellness" },
  { name: "Fitness Equipment" },
  { name: "Sports Equipment" },
  { name: "Outdoor Gear" },
  { name: "Camping & Hiking" },
  { name: "Cycling" },
  { name: "Pet Supplies" },
  { name: "Baby Products" },
  { name: "Diapers" },
  { name: "Baby Clothing" },
  { name: "Toys for Babies" },
  { name: "Food & Beverages" },
  { name: "Gourmet Foods" },
  { name: "Organic Foods" },
  { name: "Snacks" },
  { name: "Beverages" },
  { name: "Coffee & Tea" },
  { name: "Alcoholic Beverages" },
  { name: "Automotive" },
  { name: "Car Accessories" },
  { name: "Motorcycle Accessories" },
  { name: "Tires & Wheels" },
  { name: "Car Electronics" },
  { name: "Music Instruments" },
  { name: "Office Electronics" },
  { name: "Printers & Scanners" },
  { name: "Networking Devices" },
  { name: "Smart Home Devices" },
  { name: "Home Security" },
  { name: "Cleaning Supplies" },
  { name: "Party Supplies" },
  { name: "Arts & Crafts" },
  { name: "Sewing & Knitting" },
  { name: "Scrapbooking" },
  { name: "Collectibles" },
  { name: "Memorabilia" },
  { name: "Antiques" },
  { name: "Industrial Equipment" },
  { name: "Safety & Security" },
  { name: "Janitorial Supplies" },
  { name: "Lab & Scientific" },
  { name: "Medical Supplies" },
  { name: "Pharmaceuticals" },
  { name: "Vision Care" },
  { name: "Hearing Aids" },
  { name: "Mobility Aids" },
  { name: "Travel Accessories" },
  { name: "Souvenirs" },
  { name: "Educational Supplies" },
  { name: "School Supplies" },
  { name: "Uniforms" },
  { name: "Religious Items" },
  { name: "Cultural Items" },
  { name: "Seasonal Decorations" },
  { name: "Event Tickets" },
  { name: "Gift Cards" },
  { name: "Subscription Services" },
  { name: "Digital Services" },
  { name: "Software" },
  { name: "DIY Kits" },
];
